<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0"
    xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="webshop_builder_3k_model"
    nsURI="http://webshop_builder_3k_model/1.0" nsPrefix="webshop_builder_3k_model">
  <eClassifiers xsi:type="ecore:EClass" name="Page">
    <eStructuralFeatures xsi:type="ecore:EReference" name="components" lowerBound="1"
        upperBound="-1" eType="#//Component" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="reuse_components" upperBound="-1"
        eType="#//Reuse_component" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="width" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="title" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="height" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="canvas_color" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="style" eType="#//Style"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Reuse_component">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="xposition" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="yposition" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Component" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="xposition" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="yposition" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="width" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="height" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="alignment" eType="#//Alignment"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="style" eType="#//Style"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Picture" eSuperTypes="#//Component">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="source" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="title" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="alternative_text" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Text_field" eSuperTypes="#//Component">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="header_level" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="text" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="User_input_field" eSuperTypes="#//Component">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="label" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Knowledge_base">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="xml_file_uri" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Item_to_KB_link">
    <eStructuralFeatures xsi:type="ecore:EReference" name="item" lowerBound="1" eType="#//Item"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="knowledge_base" lowerBound="1"
        eType="#//Knowledge_base"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Checkbox" eSuperTypes="#//User_input_field"/>
  <eClassifiers xsi:type="ecore:EClass" name="Branding" eSuperTypes="#//Component">
    <eStructuralFeatures xsi:type="ecore:EReference" name="company_name" lowerBound="1"
        eType="#//Text_field" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="company_logo" lowerBound="1"
        eType="#//Picture" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Radio_button" eSuperTypes="#//User_input_field"/>
  <eClassifiers xsi:type="ecore:EClass" name="Text_input_field" eSuperTypes="#//User_input_field"/>
  <eClassifiers xsi:type="ecore:EClass" name="Reuses_component_link">
    <eStructuralFeatures xsi:type="ecore:EReference" name="source" lowerBound="1"
        eType="#//Reuse_component"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="target" lowerBound="1"
        eType="#//Component"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Webshop_builder_3k">
    <eStructuralFeatures xsi:type="ecore:EReference" name="pages" upperBound="-1"
        eType="#//Page" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="free_components" upperBound="-1"
        eType="#//Component" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="knowledge_bases" lowerBound="1"
        upperBound="-1" eType="#//Knowledge_base" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="item_to_kb" upperBound="-1"
        eType="#//Item_to_KB_link" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="reuse_link" upperBound="-1"
        eType="#//Reuses_component_link" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="item_list_page" lowerBound="1"
        eType="#//Item_list_page" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="item_detail_page" eType="#//Item_detail_page"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="navigation_to_page_link"
        upperBound="-1" eType="#//Navigation_to_Page_link" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="company_name" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Item" eSuperTypes="#//Component">
    <eStructuralFeatures xsi:type="ecore:EReference" name="item_picture" lowerBound="1"
        eType="#//Picture" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="text_fields" lowerBound="1"
        upperBound="-1" eType="#//Text_field" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Login_widget"/>
  <eClassifiers xsi:type="ecore:EClass" name="Slideshow"/>
  <eClassifiers xsi:type="ecore:EClass" name="Social_button"/>
  <eClassifiers xsi:type="ecore:EClass" name="Newsletter_subscription_widget"/>
  <eClassifiers xsi:type="ecore:EClass" name="Shopping_cart_button"/>
  <eClassifiers xsi:type="ecore:EClass" name="Search_widget"/>
  <eClassifiers xsi:type="ecore:EClass" name="Menu"/>
  <eClassifiers xsi:type="ecore:EClass" name="Component_group"/>
  <eClassifiers xsi:type="ecore:EClass" name="Result_list" eSuperTypes="#//Component">
    <eStructuralFeatures xsi:type="ecore:EReference" name="result_template" lowerBound="1"
        eType="#//Item" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="number_of_items_per_page"
        lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="distance_between_items"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Source_code"/>
  <eClassifiers xsi:type="ecore:EClass" name="Item_detail_page" eSuperTypes="#//Page">
    <eStructuralFeatures xsi:type="ecore:EReference" name="item" lowerBound="1" eType="#//Item"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Item_list_page" eSuperTypes="#//Page">
    <eStructuralFeatures xsi:type="ecore:EReference" name="results" lowerBound="1"
        eType="#//Result_list" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Navigation_button" eSuperTypes="#//Component">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="text" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Navigation_to_Page_link">
    <eStructuralFeatures xsi:type="ecore:EReference" name="Source" lowerBound="1"
        eType="#//Navigation_button"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="target" lowerBound="1"
        eType="#//Page"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Style">
    <eStructuralFeatures xsi:type="ecore:EReference" name="border" eType="#//Border"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="background_color" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Border">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="thickness" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="color" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="Alignment">
    <eLiterals name="left"/>
    <eLiterals name="right" value="1"/>
  </eClassifiers>
</ecore:EPackage>
